OrdererOrgs:
  - Name: Orderer
    Domain: ehr.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Hospital
    Domain: hospital.ehr.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Patient
    Domain: patient.ehr.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
